### ISSUE TITLE
done_cards method in Round model

### ISSUE THREAD

**Issue by jeder28** [kimchanyoung/web-flashcards#32]
Tested this method in irb and it does not actually subtract any correctly answered cards

**Comment by jkrth617** [comment]
@jeder28 what does it do? the Done_card method should only return an array of card objects all of which are answered correctly. The controller then does the subtraction to find the array off cards that are yet to be answered

**Comment by jeder28** [comment]
I thought this was a bug when I had the round being created in the guess controller, now it works with my New pull request, please disregard.
